### ISSUE TITLE
How to train yolo9000?

### ISSUE THREAD

**Issue by xlxlcyRuSReXxlxl** [philipperemy/yolo-9000#11]
Using the pre trained yolo9000 model with Python  I notice that is much less accurate than yolov2, and I guess it's normal because it has to detect more classes. Right now I am looking for detecting landscapes (as sea shore, lake shore, mountains, deserts and things like these), so I was wondering if you could give me some guidelines to train the weights since I have no background in this. Beside the code I would like to know a good sample size for each class and the if it takes a long time with a fairly good machine. Thank you a lot !

**Comment by philipperemy** [comment]
@xlxlcyRuSReXxlxl that's a very good question for which I don't have the answer. 

This project does not contain the source code of Yolo.

In your case, you should ask directly to the guys here:
https://groups.google.com/forum/#!forum/darknet

Also if you find out how to do that, that would be interested to include it inside this repository!

Thanks!

**Comment by xiaoxiongli** [comment]
@xlxlcyRuSReXxlxl Do you successfully train yolo9000？ can you give me some tips about how to train yolo9000?
