### ISSUE TITLE
where is the yolo9000.weights?

### ISSUE THREAD

**Issue by JayYangSS** [philipperemy/yolo-9000#12]
Hi, I can't find the yolo9000.weights under the directory of `yolo-9000-weights`, can you provide this file? Thanks!

**Comment by philipperemy** [comment]
@JayYangSS It's contained in `xaa` and `xab`.

Run this command on a UNIX system to generate the file:

```
cat yolo9000-weights/x* > yolo9000-weights/yolo9000.weights
```

The reason why I did that was because of Github's max file policy (max. 100MB)

**Comment by rustynothappy** [comment]
why is it not working on other images  ?only working on dog,person,horses images

try to pas other image and plz update me on same.

**Comment by philipperemy** [comment]
@rustynothappy no it works well on almost any other image (it might require a bit of tuning for your application).

<img width="721" alt="image" src="https://user-images.githubusercontent.com/4516927/159818472-6ead0b67-ba0c-4dab-982f-49ffe144df66.png">

The image I used: http://www.experian.com/blogs/news/wp-content/uploads/2012/06/cars.png

**Comment by rustynothappy** [comment]
[yolo_9000.zip](https://github.com/philipperemy/yolo-9000/files/8339696/yolo_9000.zip)
why is it not working on mine .
see this file, and plz correct me.
