### ISSUE TITLE
Fails to identify objects that where picked up prior with yolo.weights

### ISSUE THREAD

**Issue by rnunziata** [philipperemy/yolo-9000#13]
Fails to identify objects that where picked up prior with yolo.weights. Old system idenified books in this photo. It seems to skip over small objects.
![2017-09-11-123956](https://user-images.githubusercontent.com/5377074/30293469-7f254a0c-96ee-11e7-975e-179c914f3cab.jpg)

**Comment by philipperemy** [comment]
@rnunziata YOLO 9000 is less precise than the YOLO V2. Its mAP is lower.

But it can recognize a lot more objects. Try to decrease the threshold when you do inference:

`-thresh 0.15`

Also please do refer to this conversation for more information: https://github.com/philipperemy/yolo-9000/issues/3

Thanks

**Comment by rnunziata** [comment]
Thanks
