### ISSUE TITLE
Demo needs OpenCV for webcam images.

### ISSUE THREAD

**Issue by KyrieHee** [philipperemy/yolo-9000#17]
what means about this?

**Comment by philipperemy** [comment]
The whole project needs openCV.

```
sudo apt-get install libopencv-dev python-opencv
```

And you will be fine

**Comment by KyrieHee** [comment]
I will try it, Thank you so much.

At 2017-12-19 22:59:43, "Philippe Rémy" <notifications@github.com> wrote:


The whole project needs openCV.

sudo apt-get install libopencv-dev python-opencv


And you will be fine

**Comment by KyrieHee** [comment]
Ok, Thank you so much.

**Comment by philipperemy** [comment]
Ok great!
