### ISSUE TITLE
nan issue.

### ISSUE THREAD

**Issue by evenctit** [philipperemy/yolo-9000#20]
hi Philip, 
I follow the formal website _https://pjreddie.com/darknet/yolo/_ to run yolo9000 to detect text in nature scene, I updated the configurations, however, when I tried to train the model, I got below error, do you have any idea what's the root cause? 
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000321, Avg Recall: -nan,  count: 0
80195: 0.000204, 0.000202 avg, 0.000010 rate, 0.124108 seconds, 80195 images
Loaded: 0.000039 seconds

**Comment by philipperemy** [comment]
Hum really have no idea. Maybe the community can help you @evenctit

**Comment by philipperemy** [comment]
Can you run the example in the README file?

**Comment by philipperemy** [comment]
I'll close this issue. I have never encountered any nan so far.
