### ISSUE TITLE
FPS is slow

### ISSUE THREAD

**Issue by Dawson-huang** [philipperemy/yolo-9000#21]
My command is:
./darknet detector demo cfg/combine9k.data cfg/yolo9000.cfg ../yolo9000-weights/yolo9000.weights 
but the FPS is very slow:       FPS:1.6
It run on GTX 1080 and the CPU is 3.2GHz.
How to reflect better, faster and stronger？

**Comment by philipperemy** [comment]
Can you run `watch -n0.01 nvidia-smi` and see the usage, especially the `Volatile GPU-Util` flag?

**Comment by Dawson-huang** [comment]
Hello,
This is my nvidia-smi when I run  [ watch -n0.01 nvidia-smi ] :
![2018-03-19 14-50-57](https://user-images.githubusercontent.com/31092966/37582557-8f08b0a6-2b88-11e8-9347-2e422e6e593e.png)

The same command: 
    ./darknet detector demo cfg/combine9k.data cfg/yolo9000.cfg ../yolo9000-weights/yolo9000.weights
It alse run on GTX 1080 and the CPU is 3.2GHz.
FPS=3.3

**Comment by philipperemy** [comment]
How much is Volatile GPU Util on average during 1minute? (On your screenshot it was 3%)

**Comment by philipperemy** [comment]
I'll close this issue. Feel free to reopen it if you have questions.
