### ISSUE TITLE
List of 9000 classes?

### ISSUE THREAD

**Issue by smich73** [philipperemy/yolo-9000#23]
Hi Philippe
Do you have a list of the 9000 objects/classes that this version of Yolo recognises?

Thanks

**Comment by philipperemy** [comment]
Hey,

The classes names are available here:

- https://github.com/pjreddie/darknet/blob/1e729804f61c8627eb257fba8b83f74e04945db7/data/9k.names

**Comment by Zeeshan75** [comment]
Did anyone have the trained model on these 9k classes?

**Comment by rahul-tiwari-Singleinterface** [comment]
Hi Philippe,
Can you suggest the dataset for shop category. I tried few of my own but unfortunately the model was not able to recognise them.

Thanks in advance !!

**Comment by vyasn30** [comment]
> 
> 
> Hey,
> 
> The classes names are available here:
> 
>     * https://github.com/pjreddie/darknet/blob/1e729804f61c8627eb257fba8b83f74e04945db7/data/9k.names

So one can detect any object from that list? That is insane

**Comment by philipperemy** [comment]
@vyasn30 yes that's correct!
