### ISSUE TITLE
Keep Getting Wrong Label Names

### ISSUE THREAD

**Issue by tangziqiao** [philipperemy/yolo-9000#24]
Hello, I'm wondering if anyone knows why I keep getting these incorrect names which are not suppose to be the names under the 9k.names file???
This was the result when I set the threshold to 0.

<img width="794" alt="screen shot 2018-03-21 at 22 56 43" src="https://user-images.githubusercontent.com/31482447/37750482-4925af06-2d5b-11e8-886b-9c317d8a4dd0.png">

Any idea why this happened??

**Comment by philipperemy** [comment]
I guess you should not put the threshold to 0 otherwise you will have all the possible names popping up everywhere.
