### ISSUE TITLE
How to save the coordinates of the bounding boxes ?

### ISSUE THREAD

**Issue by vismayaps** [philipperemy/yolo-9000#29]
Hi,

How can I save/print the coordinated of the bounding boxes detected ? 
I made some changes on src/image.c to print the coordinates of the bounding boxes in darknet, but the same changes doesn't work here and the code also looks different.

Any help would be appreciated.
Thanks in Advance !!

**Comment by philipperemy** [comment]
Hum I'm not sure here. The framework is exactly the same. Only checkpoints and configuration files are different for YOLO9000. So you should still be able to print the bounding boxes in darknet (maybe in src/image.c).

**Comment by akshaybhatia10** [comment]
Make sure to run the 'make' command for the changes to come into effect.
