### ISSUE TITLE
when loading image, there is core dump when video reaches its end.

### ISSUE THREAD

**Issue by fzhu129** [philipperemy/yolo-9000#30]
Hi 

I run this script:

./darknet detector demo cfg/combine9k.data cfg/yolo9000.cfg ../yolo9000-weights/yolo9000.weights -prefix IL /data/videos/ILSVRC2015_train_00755001.mp4 -thresh 0.15

It is found that it will have core dump when video ends.

(gdb) bt
#0  0x00007f9d00875478 in malloc_consolidate (av=av@entry=0x7f9d00bbbb20 <main_arena>) at malloc.c:4175
#1  0x00007f9d00878cde in _int_malloc (av=av@entry=0x7f9d00bbbb20 <main_arena>, bytes=bytes@entry=2764824) at malloc.c:3450
#2  0x00007f9d0087b184 in __GI___libc_malloc (bytes=2764824) at malloc.c:2913
#3  0x00007f9cfb5894c0 in ?? () from /usr/lib/nvidia-396/tls/libnvidia-tls.so.396.26
#4  0x00007f9d1d28e43e in cv::fastMalloc(unsigned long) () from /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4
#5  0x00007f9d1d209c8d in cvCreateData () from /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4
#6  0x00007f9d1d217041 in cvCreateImage () from /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4
#7  0x0000000000420f4c in save_image_jpg (p=..., name=0x7fff3efcea10 "IL_00000030") at ./src/image.c:520
#8  0x00000000004212bf in save_image (im=..., name=0x7fff3efcea10 "IL_00000030") at ./src/image.c:558
#9  0x0000000000470222 in demo (cfgfile=0x7fff3efcf11f "cfg/yolo9000.cfg", weightfile=0x7fff3efcf130 "../yolo9000-weights/yolo9000.weights", thresh=0.150000006, cam_index=0, 
    filename=0x7fff3efcf160 "/data/videos/ILSVRC2015_train_00755001.mp4", names=0x260c190, classes=9418, frame_skip=0, prefix=0x7fff3efcf15d "IL", hier_thresh=0.5)
    at ./src/demo.c:183
#10 0x000000000045565e in run_detector (argc=11, argv=0x7fff3efced18) at ./src/detector.c:550
#11 0x000000000043d600 in main (argc=11, argv=0x7fff3efced18) at ./src/darknet.c:384

Any ideas?
Frank

**Comment by philipperemy** [comment]
Looks like it's a memory issue. Do you have enough RAM?
