### ISSUE TITLE
FFMPEG error making own video on Ubuntu

### ISSUE THREAD

**Issue by sophia-wright-blue** [philipperemy/yolo-9000#33]
I get the following error on trying to make my own video on Ubuntu with GPU

```
mask_scale: Using default '1.000000'
Loading weights from ../yolo9000-weights/yolo9000.weights...Done!
video file: /test_videos/demo.mp4
[ WARN:0] cvCreateFileCaptureWithPreference: backend FFMPEG doesn't support legacy API anymore.
Unable to stop the stream: Function not implemented
Couldn't connect to webcam.
: Function not implemented
darknet: ./src/utils.c:224: error: Assertion `0' failed.
Aborted (core dumped)
```

any help fixing this will be greatly appreciated.

Thanks,

**Comment by philipperemy** [comment]
Hum not sure on how to solve this one. Seems like an OpenCV issue.

**Comment by sophia-wright-blue** [comment]
thanks for replying @philipperemy , i'll look into this some more,

**Comment by philipperemy** [comment]
@sophia-wright-blue let us know when you found the fix!

**Comment by MounirB** [comment]
You can find a solution here maybe : [cvcreatefilecapturewithpreference warning](https://answers.opencv.org/question/204785/blank-video-and-error-message-warn0-cvcreatefilecapturewithpreference-backend-msmf-doesnt-support-legacy-api-anymore/)

**Comment by philipperemy** [comment]
@MounirB thanks for sharing!

**Comment by VQHieu1012** [comment]
can you fix it yet?
