### ISSUE TITLE
Not able to detect the object for some images

### ISSUE THREAD

**Issue by sohambannerjee8** [philipperemy/yolo-9000#44]
When I am trying to run the below command it is not returning the value for some images.I have provided the image link in the  end. @philipperemy 
`
./darknet detector test cfg/combine9k.data cfg/yolo9000.cfg ../yolo9000-weights/yolo9000.weights /home/arc/darknet/my.jpg`

> layer     filters    size              input                output
>     0 conv     32  3 x 3 / 1   544 x 544 x   3   ->   544 x 544 x  32  0.511 BFLOPs
>     1 max          2 x 2 / 2   544 x 544 x  32   ->   272 x 272 x  32
>     2 conv     64  3 x 3 / 1   272 x 272 x  32   ->   272 x 272 x  64  2.727 BFLOPs
>     3 max          2 x 2 / 2   272 x 272 x  64   ->   136 x 136 x  64
>     4 conv    128  3 x 3 / 1   136 x 136 x  64   ->   136 x 136 x 128  2.727 BFLOPs
>     5 conv     64  1 x 1 / 1   136 x 136 x 128   ->   136 x 136 x  64  0.303 BFLOPs
>     6 conv    128  3 x 3 / 1   136 x 136 x  64   ->   136 x 136 x 128  2.727 BFLOPs
>     7 max          2 x 2 / 2   136 x 136 x 128   ->    68 x  68 x 128
>     8 conv    256  3 x 3 / 1    68 x  68 x 128   ->    68 x  68 x 256  2.727 BFLOPs
>     9 conv    128  1 x 1 / 1    68 x  68 x 256   ->    68 x  68 x 128  0.303 BFLOPs
>    10 conv    256  3 x 3 / 1    68 x  68 x 128   ->    68 x  68 x 256  2.727 BFLOPs
>    11 max          2 x 2 / 2    68 x  68 x 256   ->    34 x  34 x 256
>    12 conv    512  3 x 3 / 1    34 x  34 x 256   ->    34 x  34 x 512  2.727 BFLOPs
>    13 conv    256  1 x 1 / 1    34 x  34 x 512   ->    34 x  34 x 256  0.303 BFLOPs
>    14 conv    512  3 x 3 / 1    34 x  34 x 256   ->    34 x  34 x 512  2.727 BFLOPs
>    15 conv    256  1 x 1 / 1    34 x  34 x 512   ->    34 x  34 x 256  0.303 BFLOPs
>    16 conv    512  3 x 3 / 1    34 x  34 x 256   ->    34 x  34 x 512  2.727 BFLOPs
>    17 max          2 x 2 / 2    34 x  34 x 512   ->    17 x  17 x 512
>    18 conv   1024  3 x 3 / 1    17 x  17 x 512   ->    17 x  17 x1024  2.727 BFLOPs
>    19 conv    512  1 x 1 / 1    17 x  17 x1024   ->    17 x  17 x 512  0.303 BFLOPs
>    20 conv   1024  3 x 3 / 1    17 x  17 x 512   ->    17 x  17 x1024  2.727 BFLOPs
>    21 conv    512  1 x 1 / 1    17 x  17 x1024   ->    17 x  17 x 512  0.303 BFLOPs
>    22 conv   1024  3 x 3 / 1    17 x  17 x 512   ->    17 x  17 x1024  2.727 BFLOPs
>    23 conv  28269  1 x 1 / 1    17 x  17 x1024   ->    17 x  17 x28269  16.732 BFLOPs
>    24 detection
> mask_scale: Using default '1.000000'
> Loading weights from ../yolo9000-weights/yolo9000.weights...Done!
> /home/arc/darknet/my.jpg: Predicted in 9.645303 [seconds.]

[Image URL](https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/golden-retriever-royalty-free-image-506756303-1560962726.jpg?crop=0.669xw:1.00xh;0.166xw,0&resize=640:*)

**Comment by LilianLiang7** [comment]
try to set  smaller  thresh for detection may help

**Comment by sohambannerjee8** [comment]
@LilianLiang7  I  got the result with .2 threshold .

**Comment by philipperemy** [comment]
I'll close this issue if it's solved. Thank you!
