### ISSUE TITLE
how to use this yolo 9000 in ios?

### ISSUE THREAD

**Issue by steve21124** [philipperemy/yolo-9000#5]

**Comment by philipperemy** [comment]
@steve21124 that's a very good question! I have absolutely no clue. Do you think you can port it to iOS? The source code is in C.

**Comment by philipperemy** [comment]
What you could do instead is to stream it from the iOS device to a remote server and get back the bounding boxes. I know it works in real time. Find some more info on the author's website: https://pjreddie.com/darknet/

**Comment by steve21124** [comment]
thanks. I found more info. https://github.com/hollance/Forge/blob/99a2bb42448d89827c9d7ae872209bad0a610574/Examples/YOLO/yolo2metal.py

the above convert yolo to metal which is supported by ios. I am not sure if I can convert yolo 9000 model directly to coreml
