### ISSUE TITLE
yolo9000 train and test

### ISSUE THREAD

**Issue by dereyly** [philipperemy/yolo-9000#6]
Paper yolo9000 is very nice with many points. One of points is task to classify many classes and solution with composite softmax.
How can I repeat this experiment? and try my own solutions on this task (9000 classes)?
Do you have plan to create this benchmark as open?

**Comment by philipperemy** [comment]
This project does not contain the source code of Yolo. It only contains deployment scripts to make the magic happen!

In your case, you should ask directly to the guys here:

https://groups.google.com/forum/#!forum/darknet

**Comment by dereyly** [comment]
Thank you @philipperemy I try it )
