### ISSUE TITLE
memory requirements

### ISSUE THREAD

**Issue by mhnatiuk** [philipperemy/yolo-9000#9]
Are memory requirements for running detection on yolo-9000 higher than yolov2 on coco? If so, can someone provide an estimate for memory req.?

**Comment by philipperemy** [comment]
I have no idea of yolov2. But on my experiments, yolo 9000 uses around 4206MiB on the GPU. So it should not be a problem if your GPUs have more than 6-8GB.

**Comment by philipperemy** [comment]
If the model is equivalent to yolo v2, then the memory footprint should be the same. (The memory allocated is not proportional to the size of the data).

So I guess yolo v2 and yolo 9000 should be pretty similar since they share almost the same architecture (from what I remember).

**Comment by ThibaultGROUEIX** [comment]
I'm running it on 6GB with 562MB already taken for the desktop and i get an out of memory. I guess i must be slightly under the requirements.

**Comment by philipperemy** [comment]
@ThibaultGROUEIX thanks for the feedback! As you said, I guess 6GB is the limit. I think it would work if you didn't have your Desktop app running on the same GPU.

I can confirm it works flawlessly on a 8GB GPU (GTX 1070).

**Comment by philipperemy** [comment]
I added a note in the README file: 73e54e951f7b5b87ee88a91ce93415f4f90f09bf

Despite the fact that it can work with 6GB, I prefer to recommend 8GB.
